[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
  loki-k8s/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
  loki-k8s/0 [executing] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model          Controller                Cloud/Region        Version  SLA          Timestamp
test-cos-h2a4  github-pr-c1a48-microk8s  microk8s/localhost  3.6.8    unsupported  08:53:51Z

App             Version  Status  Scale  Charm           Channel   Rev  Address         Exposed  Message
loki-k8s        2.9.6    active      1  loki-k8s        1/stable  199  10.152.183.91   no       
prometheus-k8s  2.52.0   active      1  prometheus-k8s  1/stable  247  10.152.183.197  no       
vault-k8s                active      3  vault-k8s                   0  10.152.183.161  no       

Unit               Workload  Agent  Address      Ports  Message
loki-k8s/0*        active    idle   10.1.63.223         
prometheus-k8s/0*  active    idle   10.1.63.222         
vault-k8s/0*       active    idle   10.1.63.210         
vault-k8s/1        active    idle   10.1.63.216         
vault-k8s/2        active    idle   10.1.63.219         

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-loki-k8s-0: 08:50:24 ERROR juju.worker.uniter pebble poll failed for container "node-exporter": failed to send pebble-ready event: terminated
unit-vault-k8s-1: 08:50:26 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-cos-h2a4.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1da3a80350>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-0: 08:50:36 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
model-afb753f9-24aa-4a77-8366-3400cccbcbb4: 08:50:36 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-1: 08:50:36 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-2: 08:50:37 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent

[32mINFO    [0m pytest_operator.plugin:plugin.py:1063 Resetting model test-cos-h2a4...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications prometheus-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications loki-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1068 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...