[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
  loki-k8s/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
  loki-k8s/0 [executing] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model          Controller                Cloud/Region        Version  SLA          Timestamp
test-cos-ja17  github-pr-12d28-microk8s  microk8s/localhost  3.6.8    unsupported  00:00:59Z

App             Version  Status  Scale  Charm           Channel   Rev  Address         Exposed  Message
loki-k8s        2.9.6    active      1  loki-k8s        1/stable  199  10.152.183.110  no       
prometheus-k8s  2.52.0   active      1  prometheus-k8s  1/stable  247  10.152.183.139  no       
vault-k8s                active      3  vault-k8s                   0  10.152.183.217  no       

Unit               Workload  Agent  Address      Ports  Message
loki-k8s/0*        active    idle   10.1.63.222         
prometheus-k8s/0*  active    idle   10.1.63.223         
vault-k8s/0*       active    idle   10.1.63.208         
vault-k8s/1        active    idle   10.1.63.219         
vault-k8s/2        active    idle   10.1.63.217         

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-vault-k8s-2: 23:57:42 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-cos-ja17.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16bbb7cd40>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 23:57:53 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 23:57:53 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-1: 23:57:53 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: write tcp 10.1.63.219:51704->10.152.183.123:17070: write: broken pipe: write tcp 10.1.63.219:51704->10.152.183.123:17070: write: broken pipe
model-10725a34-5dd6-45df-8f25-a250408e9ea6: 23:57:53 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent

[32mINFO    [0m pytest_operator.plugin:plugin.py:1063 Resetting model test-cos-ja17...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications prometheus-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications loki-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1068 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...